language: php

php:
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer require php-coveralls/php-coveralls
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
