language: php

php:
  - 7.1
  - nightly

install:
  - composer require php-coveralls/php-coveralls
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - chmod +x /home/forge/stigquotes.com/deploy.sh; /home/forge/stigquotes.com/deploy.sh
